config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard/cards#index'

  scope module: 'home' do
    get 'login' => 'user_sessions#new', :as => :login
    get 'oauth/callback' => 'oauths#callback'
    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
    resources :users, only: [:new, :create]
    resources :user_sessions, only: [:new, :index, :create]
  end

  scope module: 'dashboard' do
    post 'logout' => 'user_sessions#destroy', :as => :logout
    get '/cards/admin' => 'cards#admin'
    get '/remove_attachment' => 'cards#remove_attachment'
    post '/check' => 'cards#check'
    resources :cards, :decks, :users, :user_sessions
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessor :user_entered
  belongs_to :user
  belongs_to :deck
  has_attached_file :picture, styles: { medium: '360x360>', thumb: '100x100>' },
                              default_url: '/images/:style/missing.png'
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  validates :original_text, :translated_text, :review_date, :deck_id,
            presence: true
  validate :values_cannot_be_equal

  scope :review_expired, -> { where('review_date <=?', Time.now) }

  def check_translation(guess)
    if Levenshtein.distance(original_text.downcase, guess.downcase) <= 2
      msg = (I18n.t('flash.mistyped')).concat(': ').concat(original_text).
        concat(I18n.t('flash.you_entered')).concat(': ').concat(guess)
    end
    { correct: original_text.downcase == guess.downcase, message: msg }
  end

  def manage_review_dates(time, correct)
    updater = CardReviewUpdater.new(time, correct, efactor)
    quality = updater.quality
    repeat = quality < 4
    total_reps = quality < 3 ? 1 : repetition_total + 1
    interval = updater.get_interval(total_reps)

    update(review_date: interval.days.from_now, efactor: updater.efactor,
                             repeat_later: repeat, repetition_total: total_reps)
  end

  private

  def values_cannot_be_equal
    if translated_text.downcase.eql?(original_text.downcase)
      errors.add(:translated_text,
                 "Поля 'Оригинальный текст' и 'Переведенный текст' не должны совпадать")
    end
  end
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ApplicationController
  before_filter :require_login

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < Dashboard::ApplicationController
  def index
    @card = current_user.take_card
    unless @card
      flash.keep[:info] = (t 'flash.no_cards')
      redirect_to cards_admin_path
    end
  end

  def edit
    @card = current_user.cards.find(params[:id])
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    redirect_to cards_admin_path
  end

  def new
    @card = Card.new
  end

  def admin
    @cards = current_user.cards
  end

  def show
    redirect_to cards_admin_path
  end

  def check
    @card = Card.find(params[:card][:id])
    result = @card.check_translation(params[:card][:user_entered])
    setup_flash(result)
    @card.manage_review_dates(params[:elapsed], result[:correct])
    respond
  end

  def update
    @card = Card.find(params[:id])
    @card.update(card_params)

    redirect_to cards_admin_path
  end

  def create
    @card = Card.new(card_params)
    @card.user = current_user

    if @card.save
      redirect_to cards_admin_path
    else
      render 'new'
    end
  end

  def remove_attachment
    @card = Card.find(params[:id])
    @card.picture = nil
    @card.save
    redirect_to edit_card_path(@card)
  end

  private

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :user_id, :picture, :deck_id)
  end

  def respond
    current_user.review_complete
    @card = current_user.take_card
    respond_to do |format|
      if @card
        flash.discard
        format.js
      else
        @cards = current_user.cards
        format.js {render "admin"}
        flash.keep[:info] = (t 'flash.no_cards')
        flash.discard
      end
    end
  end

  def setup_flash(response)
    if response[:correct]
      flash[:success] = (t 'flash.answer_correct')
    else
      flash[:danger] = (t 'flash.answer_wrong')
      flash[:warning] = response[:message] if response[:message]
    end
  end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < Dashboard::ApplicationController
  def new
    @deck = Deck.new
  end

  def index
    @decks = current_user.decks
  end

  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy

    redirect_to decks_path
  end

  def create
    @deck = Deck.new(deck_params)
    @deck.user = current_user

    if @deck.save
      redirect_to decks_path
    else
      render 'new'
    end
  end

  def update
    @deck = Deck.find(params[:id])
    if @deck.update(deck_params)
      redirect_to decks_path
    else
      flash[:danger] = @deck.errors[:current]
      redirect_to edit_deck_path(@deck)
    end
  end

  def edit
    @deck = Deck.find(params[:id])
  end

  private

  def deck_params
    params.require(:deck).permit(:name, :current, :user_id)
  end
end

app/controllers/dashboard/user_sessions_controller.rb
class Dashboard::UserSessionsController < Dashboard::ApplicationController
  def destroy
    logout
    redirect_to(:root, success: (t 'flash.signout'))
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::ApplicationController
  def index
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params) ? (redirect_to users_path) : (render 'edit')
  end

  private

  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation,:authentications_attributes, :locale)
  end
end

app/views/dashboard/cards/_admin.html.erb
<% flash.each do |key, value| %>
   <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
<% end %>
<table class="table table-hover table-condensed">
  <tr>
    <th><%= t '.number' %></th>
    <th><%= t '.id' %></th>
    <th><%= t '.deck' %></th>
    <th><%= t '.original' %></th>
    <th><%= t '.translation' %></th>
    <th><%= t '.rev_date' %></th>
    <th><%= t '.img' %></th>
  </tr>

<% @cards.each_with_index do |card,index| %>
  <tr>
    <td><%= index.next %></td>
    <td><%= card.id %></td>
    <td><%= card.deck.try(:name) %></td>
    <td><%= card.original_text %></td>
    <td><%= card.translated_text %></td>
    <td><%= card.review_date.strftime("%d/%m/%Y  %H:%M:%S") %></td>
    <td><%= image_tag card.picture.url(:thumb) %></td>
    <td><%= link_to (t '.edit'), edit_card_path(card),
            class: "btn btn-default btn-sm" %></td>
    <td><%= link_to (t '.delete'), card_path(card),
            class: "btn btn-default btn-sm",
            method: :delete,
            data: { confirm: (t 'deletion_confirm') } %></td>
  </tr>
<% end %>
</table>

app/views/dashboard/cards/_form.html.erb
<div class="form-group">
  <%= simple_form_for @card do |f| %>

  <%= f.input :original_text, required: true %>
  <%= f.input :translated_text, required: true %>

  <div class="form-group">

    <%= f.input :picture, as: :file, label: (t 'dashboard.cards.admin.img') %>

    <% if @card.picture_file_name %>
      <%= image_tag @card.picture.url(:medium) %>

  </div>

  <div class="form-group">
      <%= link_to (t 'card.remove_image'), remove_attachment_path(:id => @card.id),
                      class: "btn btn-info", data: { confirm: (t 'deletion_confirm') } %>
  </div>

    <% end %>

  <%= f.input :review_date, default: {day: (-1).days.from_now.day }, required: true %>
  <%= f.input :deck_id, collection: current_user.decks, label: (t 'card.deck_choice'), required: true %>
  <%= f.button :submit, (t 'save') %>

  <% end %>
</div>

app/views/dashboard/cards/_index.html.erb
<div class="form-group">
  <%= simple_form_for @card,
      url: url_for(action: 'check', controller: 'cards'), remote: true,
      method: 'post' do |f| %>

  <%= f.input :translated_text, disabled: true %>
    <% if @card.picture_file_name %>
      <div class="form-group">
        <%= image_tag @card.picture.url(:medium) %>
      </div>
    <% end %>
  <%= f.input :user_entered, label: (t '.invite'), required: true %>
  <%= f.hidden_field :id %>
  <%= f.button :submit, (t '.check') %>

  <% end %>
</div>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
<% end %>

<div class="jumbotron text-center">
  <div class="h1" id="clock"></div>
</div>

<%= javascript_include_tag "countdown", "data-turbolinks-track" => true %>

app/views/dashboard/cards/admin.html.erb
<div id = "index_page">
  <%= render 'admin' %>
</div>

app/views/dashboard/cards/admin.js.erb
$("#index_page").html("<%= escape_javascript(render partial: 'admin', locals:{cards: @cards} ) %>"); 

app/views/dashboard/cards/check.js.erb
$("#index_page").html("<%= escape_javascript(render partial: 'index', locals:{card: @card} ) %>"); 

app/views/dashboard/cards/edit.html.erb
<h3><%= t 'dashboard.cards.admin.edit' %></h3>

<%= render 'form' %>

<%= link_to (t 'back'), cards_admin_path, class: "btn btn-default" %>

app/views/dashboard/cards/index.html.erb
<div id="index_page">
<%= render 'index' %>
</div>

app/views/dashboard/cards/new.html.erb
<h3><%= t 'card.new' %></h3>

<%= render 'form' %>

<%= link_to (t 'back'), cards_admin_path, class: "btn btn-default" %>