config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard/cards#index'

  scope module: 'home' do
    get 'login' => 'user_sessions#new', :as => :login
    get 'oauth/callback' => 'oauths#callback'
    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
    resources :users, only: [:new, :create]
    resources :user_sessions, only: [:new, :index, :create]
  end

  scope module: 'dashboard' do
    post 'logout' => 'user_sessions#destroy', :as => :logout
    get '/cards/admin' => 'cards#admin'
    get '/remove_attachment' => 'cards#remove_attachment'
    post '/check' => 'cards#check'
    resources :cards, :decks, :users, :user_sessions
  end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
  validates_uniqueness_of :current, scope: :user_id, if: :current?,
    :message=>"Текущая колода уже выбрана"

end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ApplicationController
  before_filter :require_login

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < Dashboard::ApplicationController
  def index
    @card = current_user.take_card
    unless @card
      flash.keep[:info] = (t 'flash.no_cards')
      redirect_to cards_admin_path
    end
  end

  def edit
    @card = current_user.cards.find(params[:id])
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    redirect_to cards_admin_path
  end

  def new
    @card = Card.new
  end

  def admin
    @cards = current_user.cards
  end

  def show
    redirect_to cards_admin_path
  end

  def check
    @card = Card.find(params[:card][:id])
    result = @card.check_translation(params[:card][:user_entered])
    setup_flash(result)
    @card.manage_review_dates(params[:elapsed], result[:correct])
    respond
  end

  def update
    @card = Card.find(params[:id])
    @card.update(card_params)

    redirect_to cards_admin_path
  end

  def create
    @card = Card.new(card_params)
    @card.user = current_user

    if @card.save
      redirect_to cards_admin_path
    else
      render 'new'
    end
  end

  def remove_attachment
    @card = Card.find(params[:id])
    @card.picture = nil
    @card.save
    redirect_to edit_card_path(@card)
  end

  private

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :user_id, :picture, :deck_id)
  end

  def respond
    current_user.review_complete
    @card = current_user.take_card
    respond_to do |format|
      if @card
        flash.discard
        format.js
      else
        @cards = current_user.cards
        format.js {render "admin"}
        flash.keep[:info] = (t 'flash.no_cards')
        flash.discard
      end
    end
  end

  def setup_flash(response)
    if response[:correct]
      flash[:success] = (t 'flash.answer_correct')
    else
      flash[:danger] = (t 'flash.answer_wrong')
      flash[:warning] = response[:message] if response[:message]
    end
  end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < Dashboard::ApplicationController
  def new
    @deck = Deck.new
  end

  def index
    @decks = current_user.decks
  end

  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy

    redirect_to decks_path
  end

  def create
    @deck = Deck.new(deck_params)
    @deck.user = current_user

    if @deck.save
      redirect_to decks_path
    else
      render 'new'
    end
  end

  def update
    @deck = Deck.find(params[:id])
    if @deck.update(deck_params)
      redirect_to decks_path
    else
      flash[:danger] = @deck.errors[:current]
      redirect_to edit_deck_path(@deck)
    end
  end

  def edit
    @deck = Deck.find(params[:id])
  end

  private

  def deck_params
    params.require(:deck).permit(:name, :current, :user_id)
  end
end

app/controllers/dashboard/user_sessions_controller.rb
class Dashboard::UserSessionsController < Dashboard::ApplicationController
  def destroy
    logout
    redirect_to(:root, success: (t 'flash.signout'))
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::ApplicationController
  def index
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params) ? (redirect_to users_path) : (render 'edit')
  end

  private

  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation,:authentications_attributes, :locale)
  end
end

app/views/dashboard/decks/_form.html.erb
<div class="form-group">
  <%= simple_form_for @deck do |f| %>

  <%= f.input :name %>
  <%= f.input_field :current, as: :boolean, inline_label: (Deck.human_attribute_name("current")), required: true %>
  <div class="form-group">
    <%= f.button :submit, (t 'save') %>
  </div>
  <% end %>
</div>

app/views/dashboard/decks/edit.html.erb
<h3><%= t 'dashboard.decks.index.edit' %></h3>

<%= render 'form' %>

<div class="form-group">
<%= link_to (t 'back'), decks_path, class: "btn btn-default" %>
</div>

<% flash.each do |key, value| %>
   <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
<% end %>

app/views/dashboard/decks/index.html.erb
<small><%= t '.current_row' %></small>

<% flash.each do |key, value| %>
   <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
<% end %>

<table class="table table-hover table-condensed">
  <tr>
    <th><%= t '.number' %></th>
    <th><%= t '.id' %></th>
    <th><%= t '.name' %></th>
    <th><%= t '.card_count' %></th>
  </tr>

<% @decks.each_with_index do |deck,index| %>
  <tr class="<%= 'info' if deck.current %>">
    <td><%= index.next %></td>
    <td><%= deck.id %></td>
    <td><%= deck.name %></td>
    <td><%= deck.cards.count %></td>
    <td><%= link_to (t '.edit'), edit_deck_path(deck),
            class: "btn btn-default btn-sm" %></td>
    <td><%= link_to (t '.delete'), deck_path(deck),
            class: "btn btn-default btn-sm",
            method: :delete,
            data: { confirm: (t 'deck.deletion_confirm') } %></td>
  </tr>
<% end %>
</table>
<%= link_to (t '.new'), new_deck_path,
        class: "btn btn-default" %>

app/views/dashboard/decks/new.html.erb
<h3><%= t 'dashboard.decks.index.new' %></h3>

<%= render 'form' %>

<%= link_to (t 'back'), decks_path, class: "btn btn-default" %>