config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard/cards#index'

  scope module: 'home' do
    get 'login' => 'user_sessions#new', :as => :login
    get 'oauth/callback' => 'oauths#callback'
    post 'oauth/callback' => 'oauths#callback'
    get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
    resources :users, only: [:new, :create]
    resources :user_sessions, only: [:new, :index, :create]
  end

  scope module: 'dashboard' do
    post 'logout' => 'user_sessions#destroy', :as => :logout
    get '/cards/admin' => 'cards#admin'
    get '/remove_attachment' => 'cards#remove_attachment'
    post '/check' => 'cards#check'
    resources :cards, :decks, :users, :user_sessions
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= t 'title' %></title>
  <%= stylesheet_link_tag 'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'sticky-footer', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">
            <%= t 'title' %>
          </a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li>
                <%= link_to (t 'nav.decks'), decks_path %>
              </li>
              <li>
                <%= link_to (t 'nav.cards'), cards_admin_path %>
              </li>
              <li>
                <%= link_to (t 'nav.add_card'), new_card_path %>
              </li>
              <li>
                <%= link_to (t 'nav.account'), users_path%>
              </li>
              <li>
                <%= link_to (t 'nav.signout'), :logout, method: :post %>
              </li>
            <% else %>
              <li>
                <%= link_to (t 'nav.register'), new_user_path %>
              </li>
              <li>
                <%= link_to (t 'nav.signin'), :login %>
              </li>
              <li>
                <%= link_to (t 'nav.google'),
                          auth_at_provider_path(:provider => :google) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <section class="container bs-docs-container">
      <div class="col-md-11">
        <%= yield %>
      </div>
    </section>

  </div>
    <div class="footer">
      <div class="container">
        <% unless current_user %>
          <p class="navbar-text pull-right">
            <%= link_to image_tag("/images/icon/us.png"), locale: "en" %> |
            <%= link_to image_tag("/images/icon/ru.png"), locale: "ru" %>
          </p>
        <% end %>
      </div>
    </div>
</body>

</html>